enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
build-mode = "both"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "module"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
arch = "arm64-v8a"
build-mode = "both"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'SIM spoof'"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Open links with app chooser'"

[Facebook]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/facebook/"
arch = "arm64-v8a"
build-mode = "module"

[Tasker]
app-name = "Tasker"
patches-source = "indrastorms/Dropped-Patches"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"
