enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "both"
excluded-patches = "'GmsCore support'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
build-mode = "both"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
build-mode = "both"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
build-mode = "both"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Custom branding'"
excluded-patches = "'GmsCore support'"
